spring:
  application:
    name: user-microservice
  cloud:
    config:
      uri: http://localhost:8888
      import: "optional:configserver:"
      import-check:
        enabled: false
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: info,health
  tracing:
    sampling:
      probability: 1.0
zipkin:
  endpoint: http://localhost:9411/api/v2/spans
